name: indurative

author: Trail of Bits

version: 0.0.0.1

ghc-options: -Wall -fno-warn-orphans

language: GHC2021

default-extensions:
  - OverloadedStrings

dependencies:
  - base
  - binary
  - bits-bytestring
  - bytestring
  - containers
  - cryptonite
  - finite-typelits
  - hashable
  - lens
  - memory
  - text
  - unordered-containers
  - vector

library:
  source-dirs: lib/

tests:
  indurative-test:
    source-dirs: test/
    main: Main.hs
    dependencies:
      - indurative
      - QuickCheck
      - quickcheck-instances
