name: indurative

author: JP Smith

version: 0.0.0.1

ghc-options: -Wall -fno-warn-orphans

default-extensions:
  - OverloadedStrings

dependencies:
  - array
  - base
  - binary
  - bytestring
  - containers
  - cryptonite
  - finite-typelits
  - hashable
  - lens
  - memory
  - unordered-containers
  - vector
  - vector-sized

library:
  source-dirs: lib/

tests:
  indurative-test:
    source-dirs: test/
    main: Main.hs
    dependencies:
      - indurative
      - QuickCheck
      - quickcheck-instances
